=== KDR-Games/the-path-of-theseus/src/main/resources/xml/Weapons.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Weapons (one-handed, two-handed, shields)>

<!ELEMENT one-handed (slashing, piercing, blunt)>
<!ELEMENT two-handed (slashing, piercing, blunt)>
<!ELEMENT shields (small-shield, medium-shield, tower-shield)>

<!ELEMENT slashing (weapon)+>
<!ELEMENT piercing (weapon)+>
<!ELEMENT blunt (weapon)+>

<!ELEMENT small-shield (shield)+>
<!ELEMENT medium-shield (shield)+>
<!ELEMENT tower-shield (shield)+>

<!ELEMENT weapon (name, image, damage, speed)>
<!ELEMENT shield (name, image, defense, speed)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT image (full, tile)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT defense (#PCDATA)>
<!ELEMENT speed (#PCDATA)>

<!ELEMENT full (#PCDATA)>
<!ELEMENT tile (#PCDATA)>

=== KDR-Games/the-path-of-theseus/src/main/resources/xml/Weapons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Weapons SYSTEM "Weapons.dtd">

<Weapons>
	<one-handed>
		<weapon>
			<name>Gladius</name>
			<image>gladius.png</image>
			<damage-type>slashing</damage-type>
			<damage>10</damage>
			<speed>1.3</speed>
		</weapon>
		<weapon>
			<name>Waraxe</name>
			<image>axe.png</image>
			<damage-type>slashing</damage-type>
			<damage>16</damage>
			<speed>0.9</speed>
		</weapon>
		<weapon>
			<name>Longsword</name>
			<image>longsword.png</image>
			<damage-type>slashing</damage-type>
			<damage>15</damage>
			<speed>1.0</speed>
		</weapon>

		<weapon>
			<name>Dagger</name>
			<image>dagger.png</image>
			<damage-type>piercing</damage-type>
			<damage>6</damage>
			<speed>1.7</speed>
		</weapon>
		<weapon>
			<name>Javelin</name>
			<image>javelin.png</image>
			<damage-type>piercing</damage-type>
			<damage>12</damage>
			<speed>0.9</speed>
		</weapon>
		<weapon>
			<name>Rapier</name>
			<image>rapier.png</image>
			<damage-type>piercing</damage-type>
			<damage>9</damage>
			<speed>2.0</speed>
		</weapon>

		<weapon>
			<name>Morning star</name>
			<image>morningstar.png</image>
			<damage-type>blunt</damage-type>
			<damage>22</damage>
			<speed>0.75</speed>
		</weapon>
		<weapon>
			<name>Hammer</name>
			<image>hammer.png</image>
			<damage-type>blunt</damage-type>
			<damage>13</damage>
			<speed>0.8</speed>
		</weapon>
		<weapon>
			<name>Mace</name>
			<image>mace.png</image>
			<damage-type>blunt</damage-type>
			<damage>18</damage>
			<speed>0.75</speed>
		</weapon>
	</one-handed>

	<two-handed>
		<weapon>
			<name>Greatsword</name>
			<image>greatsword.png</image>
			<damage-type>slashing</damage-type>
			<damage>33</damage>
			<speed>0.65</speed>
		</weapon>
		<weapon>
			<name>Scythe</name>
			<image>scythe.png</image>
			<damage-type>slashing</damage-type>
			<damage>28</damage>
			<speed>0.65</speed>
		</weapon>
		<weapon>
			<name>Katana</name>
			<image>katana.png</image>
			<damage-type>slashing</damage-type>
			<damage>30</damage>
			<speed>1.0</speed>
		</weapon>
		<weapon>
			<name>Greataxe</name>
			<image>greataxe.png</image>
			<damage-type>slashing</damage-type>
			<damage>35</damage>
			<speed>0.6</speed>
		</weapon>

		<weapon>
			<name>Partizan</name>
			<image>partizan.png</image>
			<damage-type>piercing</damage-type>
			<damage>25</damage>
			<speed>0.65</speed>
		</weapon>
		<weapon>
			<name>Trident</name>
			<image>trident.png</image>
			<damage-type>piercing</damage-type>
			<damage>30</damage>
			<speed>0.65</speed>
		</weapon>
		<weapon>
			<name>Spetum</name>
			<image>spetum.png</image>
			<damage-type>piercing</damage-type>
			<damage>22</damage>
			<speed>0.8</speed>
		</weapon>

		<weapon>
			<name>Warhammer</name>
			<image>warhammer.png</image>
			<damage-type>blunt</damage-type>
			<damage>40</damage>
			<speed>0.5</speed>
		</weapon>
		<weapon>
			<name>Club</name>
			<image>club.png</image>
			<damage-type>blunt</damage-type>
			<damage>23</damage>
			<speed>0.6</speed>
		</weapon>
		<weapon>
			<name>Flail</name>
			<image>flail.png</image>
			<damage-type>blunt</damage-type>
			<damage>28</damage>
			<speed>0.55</speed>
		</weapon>
	</two-handed>

	<shields>
		<shield>
			<name>Buckler</name>
			<image>buckler.png</image>
			<defense-type>small-shield</defense-type>
			<defense>10</defense>
			<speed>1.5</speed>
		</shield>
		<shield>
			<name>Parma</name>
			<image>parma.png</image>
			<defense-type>small-shield</defense-type>
			<defense>15</defense>
			<speed>1.2</speed>
		</shield>
		<shield>
			<name>Ceremonial shield</name>
			<image>ceremonialshield.png</image>
			<defense-type>small-shield</defense-type>
			<defense>9</defense>
			<speed>1.2</speed>
		</shield>

		<shield>
			<name>Knight shield</name>
			<image>knightshield.png</image>
			<defense-type>medium-shield</defense-type>
			<defense>18</defense>
			<speed>1.0</speed>
		</shield>
		<shield>
			<name>Myrmidon shield</name>
			<image>myrmidonshield.png</image>
			<defense-type>medium-shield</defense-type>
			<defense>23</defense>
			<speed>1.1</speed>
		</shield>
		<shield>
			<name>Crest shield</name>
			<image>crestshield.png</image>
			<defense-type>medium-shield</defense-type>
			<defense>18</defense>
			<speed>1.0</speed>
		</shield>

		<shield>
			<name>Aspis</name>
			<image>aspis.png</image>
			<defense-type>tower-shield</defense-type>
			<defense>25</defense>
			<speed>0.8</speed>
		</shield>
		<shield>
			<name>Tower shield</name>
			<image>towershield.png</image>
			<defense-type>tower-shield</defense-type>
			<defense>30</defense>
			<speed>0.7</speed>
		</shield>
		<shield>
			<name>Stone shield</name>
			<image>stoneshield.png</image>
			<defense-type>tower-shield</defense-type>
			<defense>40</defense>
			<speed>0.45</speed>
		</shield>
	</shields>
</Weapons>
